version: '2'
services:
  websocket1:
    build: .
    ports:
      - "3000:3000"
    links:
      - "redis:redis"
  websocket2:
    build: .
    ports:
      - "3001:3000"
    links:
      - "redis:redis"
  redis:
    image: redis
